### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ben-haim** [ardnezar/MultiChainNodeServer#1]
Hi there,

Have you got way to run this repo pls ..
Tks,
..
ytz

**Comment by ychaim** [comment]
Hey Guys,

Is there a way to get it run pls .. Any help very appreciated :-)

ytz

**Comment by ychaim** [comment]
module.js:328
    throw err;
I'm having this issue, any help pls ?

Error: Cannot find module 'connect-flash'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/otc/MultiChainNodeServer/app.js:21:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

**Comment by ychaim** [comment]
? any help ?

**Comment by ychaim** [comment]
Is there anyway to help me pls ?
